#!/bin/ksh -ph

#Figure out location of BASEDIR
BASEDIR=${0%/bin/*}
BASEDIR=${BASEDIR:-/usr} 

PATH=/usr/bin:/usr/sbin:/bin:/sbin:${BASEDIR}/sbin:${PATH}
export PATH

NWAM_MANAGER_PROPERTIES=${BASEDIR}/lib/nwam-manager-properties
GKSU=/usr/bin/gksu
AUTHS=$(auths)

if echo $AUTHS | egrep -s '(^\*|solaris\.\*|solaris\.network\.\*|solaris\.network\.autoconf\.\*)'; then
	HAS_AUTHS="yyyy"
else
    HAS_AUTHS=""
    if echo $AUTHS | egrep -s 'solaris\.network\.autoconf\.read'; then
	HAS_AUTHS="${HAS_AUTHS}y"
    fi
    if echo $AUTHS | egrep -s 'solaris\.network\.autoconf\.wlan'; then
	HAS_AUTHS="${HAS_AUTHS}y"
    fi
    if echo $AUTHS | egrep -s 'solaris\.network\.autoconf\.select'; then
	HAS_AUTHS="${HAS_AUTHS}y"
    fi
    if echo $AUTHS | egrep -s 'solaris\.network\.autoconf\.write'; then
	HAS_AUTHS="${HAS_AUTHS}y"
    fi
fi

isRunningNWAM() {
    state_nwam=`svcs -H -o state svc:/network/physical:default 2>/dev/null`

    if [ "${state_nwam}" = "online" ]
    then
        netadm list > /dev/null 2>&1
        if (( $? == 0 )); then
            return 0
        fi
    fi

    return 1
}


if isRunningNWAM; then
    if [[ x"$HAS_AUTHS" == xyyyy ]]; then
	exec $NWAM_MANAGER_PROPERTIES "$@"
    else
	exec $GKSU "$NWAM_MANAGER_PROPERTIES $@"
    fi
fi
